doctrine:
    orm:
        entity_managers:
            default:
                connection: default
                mappings:
                    PimcoreGenericExecutionEngineBundle:
                        type: attribute
                        is_bundle: true
                        dir: "src/Entity"
                        prefix: Pimcore\Bundle\GenericExecutionEngineBundle\Entity
                        alias: PimcoreGenericExecutionEngineBundle